### ISSUE TITLE
Menudropdow pushes horizontal icon menu when it expands

### ISSUE THREAD

**Issue by lianglee** [lianglee/OhYesTheme#13]
@Francisco Aparecido
Menudropdow pushes horizontal icon menu when it expands
When you click on it it opens more low pushes the icons where contains home

**Comment by gomes2191** [comment]
![bug1](https://f.cloud.github.com/assets/4576117/2016150/8f93a7da-87cf-11e3-8f81-f2a071998256.png)

Small bug in the horizontal menu icon, menu messages incorrect syntax in start.php, which already can fix if possible send the file

**Comment by seotraining1** [comment]
We assure you this will be fixed in the next release please report any other bugs or minor issues : )

**Comment by gomes2191** [comment]
![bug2](https://f.cloud.github.com/assets/4576117/2016267/f0fa6ede-87d2-11e3-9bf9-cf4d23f6a59a.png)
Drop Down Menu moves the document body div to expand

**Comment by gomes2191** [comment]
First wanted to congratulate you guys the issue was very good, I hope there are more versions and new implemetaçoes this drop down menu would be better if it uses jquery type a fade-in, blocks of comments could also have an arrow pointing to the reviewer who commented finally are just suggestions 

I already fix the bugs reviewed here. Are just little bugs if you find som more reporting to you. congratulations on the job.

**Comment by sathish4fri** [comment]
thanks for suggestion we will take necessary step to rectify it . right we are busy thats why we are not able to update a new version ......... we make it soon .............

**Comment by gomes2191** [comment]
It would also be nice if it was used font icon instead of png icons in the horizontal menu

**Comment by lianglee** [comment]
@gomes2191  the broken url has been fixed

**Comment by JohnMuller** [comment]
Fixed downloaded latest version from github,
CC: @lianglee @gomes2191  @SZ1  @sathish4fri

**Comment by sathish4fri** [comment]
sure john @lianglee
